---
# A list of pipelines where each item is a YAML representation of https://api.go.cd/current/#the-pipeline-config-object
pipelines:
  - group: defaultGroup
    pipeline:
        label_template: ${COUNT}
        enable_pipeline_locking: false
        name: hello-world-build-1
        template: build
        materials:
          - type: git
            attributes:
              url: https://github.com/dennisgranath/HelloWorld.git
              branch: master
              auto_update: false
        parameters:
          - name: BRANCH
            value: master
  - group: hello-world
    pipeline:
        label_template: ${COUNT}
        enable_pipeline_locking: false
        name: hello-world-build-2
        template: build
        materials:
          - type: git
            attributes:
              url: https://github.com/dennisgranath/HelloWorld.git
              branch: master
              auto_update: false
        parameters:
          - name: BRANCH
            value: master
